version: "3.9"

services:
  redux-todo-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "redux-todo-db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: redux-todo-mongo

  redux-todo-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:redux-todo-mongo@redux-todo-mongo:27017/

volumes:
  redux-todo-db:
